# -*- coding: utf-8 -*-
"""summarization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQrxk1m8XDQ-KYqLqEauToPxH42MGoNu
"""

!git clone -b feature/data-collection-aiko https://github.com/johnbarraza/technology_innovation_tracking_hw4.git
import os
os.chdir('/content/technology_innovation_tracking_hw4')

"""
summarization.py
================
Genera representaciones textuales estructuradas en español de repositorios GitHub
para ser usadas como input de un LLM clasificador.

Categorías objetivo: emerging | mature | declining | experimental
"""

from __future__ import annotations

import math
import pandas as pd

# ---------------------------------------------------------------------------
# Helpers internos
# ---------------------------------------------------------------------------

def _fmt_num(value, decimals: int = 0) -> str:
    """Formatea un número con separadores de miles; maneja NaN/None."""
    try:
        if value is None or (isinstance(value, float) and math.isnan(value)):
            return "desconocido"
        if decimals == 0:
            return f"{int(value):,}".replace(",", ".")
        return f"{float(value):,.{decimals}f}".replace(",", "X").replace(".", ",").replace("X", ".")
    except (TypeError, ValueError):
        return "desconocido"


def _fmt_bool(value) -> str:
    try:
        return "sí" if bool(int(value)) else "no"
    except (TypeError, ValueError):
        return "desconocido"


def _safe(value, default="desconocido") -> str:
    if value is None:
        return default
    s = str(value).strip()
    return s if s and s.lower() not in ("nan", "none", "") else default


def _topics_text(topics) -> str:
    if topics is None:
        return "ninguno"
    if isinstance(topics, list):
        clean = [str(t).strip() for t in topics if str(t).strip()]
        return ", ".join(clean) if clean else "ninguno"
    s = str(topics).strip()
    if not s or s.lower() in ("nan", "none", "[]", ""):
        return "ninguno"
    s = s.strip("[]").replace("'", "").replace('"', "")
    parts = [p.strip() for p in s.split(",") if p.strip()]
    return ", ".join(parts) if parts else "ninguno"


def _classify_age(days) -> str:
    try:
        d = float(days)
        if d < 180:   return "muy nuevo (menos de 6 meses)"
        if d < 365:   return "nuevo (6–12 meses)"
        if d < 1095:  return "establecido (1–3 años)"
        if d < 2555:  return "maduro (3–7 años)"
        return "veterano (más de 7 años)"
    except (TypeError, ValueError):
        return "antigüedad desconocida"


def _classify_activity(days) -> str:
    try:
        d = float(days)
        if d <= 7:    return "muy reciente (<=7 días)"
        if d <= 30:   return "reciente (<=30 días)"
        if d <= 90:   return "moderada (1–3 meses)"
        if d <= 365:  return "baja (3–12 meses)"
        return "inactivo (más de un año)"
    except (TypeError, ValueError):
        return "actividad desconocida"


def _classify_velocity(vel) -> str:
    try:
        v = float(vel)
        if v >= 30:  return "muy alta"
        if v >= 15:  return "alta"
        if v >= 5:   return "moderada"
        if v >= 1:   return "baja"
        return "casi nula"
    except (TypeError, ValueError):
        return "desconocida"


def _classify_community(breadth) -> str:
    try:
        b = float(breadth)
        if b >= 0.8:  return "muy amplia"
        if b >= 0.5:  return "amplia"
        if b >= 0.3:  return "moderada"
        return "reducida"
    except (TypeError, ValueError):
        return "desconocida"


def _classify_recency(score) -> str:
    try:
        s = float(score)
        if s >= 0.8:  return "muy alto"
        if s >= 0.5:  return "alto"
        if s >= 0.3:  return "medio"
        return "bajo"
    except (TypeError, ValueError):
        return "desconocido"


def _readme_size(length) -> str:
    try:
        n = int(float(length))
        if n == 0:      return "sin README"
        if n < 500:     return f"breve ({n} caracteres)"
        if n < 3000:    return f"estándar ({n} caracteres)"
        return f"extenso ({n} caracteres)"
    except (TypeError, ValueError):
        return "desconocido"

# ---------------------------------------------------------------------------
# Función principal
# ---------------------------------------------------------------------------

def create_repository_summary(row) -> str:
    """
    Genera un resumen textual estructurado en español de un repositorio GitHub.

    Parameters
    ----------
    row : pandas.Series o dict-like
        Fila del DataFrame con las columnas del proyecto.

    Returns
    -------
    str
        Texto estructurado listo para ser procesado por un LLM clasificador.
    """

    # Identidad básica
    full_name   = _safe(row.get("full_name"),   "repositorio sin nombre")
    description = _safe(row.get("description"), "sin descripción disponible")
    language    = _safe(row.get("language"),    "no especificado")
    topics      = _topics_text(row.get("topics"))

    # Popularidad
    stars        = _fmt_num(row.get("stars"))
    forks        = _fmt_num(row.get("forks"))
    contributors = _fmt_num(row.get("contributors_count"))

    # Actividad reciente
    commits_30d = _fmt_num(row.get("commits_last_30d"))
    prs         = _fmt_num(row.get("pull_requests_count"))
    releases    = _fmt_num(row.get("releases_count"))
    has_ci      = _fmt_bool(row.get("has_ci"))

    # Métricas temporales
    repo_age = _fmt_num(row.get("repo_age_days"))
    last_act = _fmt_num(row.get("last_activity_days"))

    # Señales calculadas — texto legible
    age_label        = _classify_age(row.get("repo_age_days"))
    activity_label   = _classify_activity(row.get("last_activity_days"))
    vel_label        = _classify_velocity(row.get("commit_velocity"))
    recency_label    = _classify_recency(row.get("recency_score"))
    community_label  = _classify_community(row.get("community_breadth"))
    readme_label     = _readme_size(row.get("readme_length"))

    # Señales calculadas — valores numéricos formateados
    velocity_fmt        = _fmt_num(row.get("commit_velocity"),    decimals=1)
    recency_fmt         = _fmt_num(row.get("recency_score"),      decimals=3)
    release_cadence_fmt = _fmt_num(row.get("release_cadence"),    decimals=2)
    pr_throughput_fmt   = _fmt_num(row.get("pr_throughput"),      decimals=2)
    community_fmt       = _fmt_num(row.get("community_breadth"),  decimals=3)
    stars_growth_fmt    = _fmt_num(row.get("stars_growth_proxy"), decimals=4)

    summary = (
        f"=== RESUMEN DE REPOSITORIO GITHUB ===\n"
        f"\n"
        f"## Identificación\n"
        f"- Nombre completo: {full_name}\n"
        f"- Descripción: {description}\n"
        f"- Lenguaje principal: {language}\n"
        f"- Tópicos/etiquetas: {topics}\n"
        f"\n"
        f"## Popularidad y Alcance Social\n"
        f"- Estrellas: {stars}\n"
        f"- Forks: {forks}\n"
        f"- Contribuidores únicos: {contributors}\n"
        f"- Proxy de crecimiento de estrellas: {stars_growth_fmt}\n"
        f"\n"
        f"## Actividad de Desarrollo (Ventana Reciente)\n"
        f"- Commits en los últimos 30 días: {commits_30d}\n"
        f"- Pull requests totales: {prs}\n"
        f"- Releases publicadas: {releases}\n"
        f"- Integración continua (CI) configurada: {has_ci}\n"
        f"- Documentación (README): {readme_label}\n"
        f"\n"
        f"## Madurez Temporal\n"
        f"- Antigüedad del repositorio: {repo_age} días ({age_label})\n"
        f"- Días desde la última actividad registrada: {last_act} días — {activity_label}\n"
        f"\n"
        f"## Señales de Salud y Dinámica\n"
        f"- Velocidad de commits (promedio diario reciente): {velocity_fmt} commits/día — ritmo {vel_label}\n"
        f"- Puntuación de recencia: {recency_fmt} (nivel {recency_label})\n"
        f"- Cadencia de releases: {release_cadence_fmt} releases/mes\n"
        f"- Throughput de pull requests: {pr_throughput_fmt} PRs/mes\n"
        f"- Amplitud comunitaria (índice normalizado): {community_fmt} — comunidad {community_label}\n"
        f"\n"
        f"## Síntesis para Clasificación\n"
        f"Este repositorio ({full_name}) es un proyecto en {language} con {stars} estrellas "
        f"y {contributors} contribuidores. Su historial abarca {repo_age} días ({age_label}) "
        f"y su última actividad fue hace {last_act} días ({activity_label}). "
        f"La velocidad de commits es {vel_label} ({velocity_fmt} commits/día), "
        f"la cadencia de releases es {release_cadence_fmt}/mes y "
        f"la comunidad es {community_label}. "
        f"El score de recencia es {recency_label} ({recency_fmt}). "
        f"Basándote en estas métricas, clasifica este repositorio en una de las siguientes "
        f"categorías: [emerging, mature, declining, experimental].\n"
        f"\n"
        f"=== FIN DEL RESUMEN ==="
    )

    return summary

# ---------------------------------------------------------------------------
# Función batch
# ---------------------------------------------------------------------------

def batch_summarize(df: pd.DataFrame) -> pd.DataFrame:
    """
    Aplica create_repository_summary a cada fila del DataFrame y agrega
    la columna 'text_representation'.

    Parameters
    ----------
    df : pd.DataFrame

    Returns
    -------
    pd.DataFrame
        Copia con la columna 'text_representation' añadida.
    """
    result = df.copy()
    result["text_representation"] = result.apply(
        lambda row: create_repository_summary(row), axis=1
    )
    return result