# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfMLEIKVy2yFLyT3VT8Tyn9RkOLwx79a
"""

import os
os.chdir('/content/technology_innovation_tracking_hw4')
print(os.getcwd())

!pip install torchvision==0.19.0 --quiet

# Dependencies (run once in Colab):
!pip install transformers datasets evaluate scikit-learn accelerate torch seaborn

import os
import argparse
import json
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    DataCollatorWithPadding,
)
import evaluate

# Canonical label ordering — must match evaluation.py
LABELS = ["declining", "emerging", "experimental", "mature"]
LABEL2ID = {label: idx for idx, label in enumerate(LABELS)}
ID2LABEL = {idx: label for idx, label in enumerate(LABELS)}
NUM_LABELS = len(LABELS)
MODEL_NAME = "distilbert-base-uncased"


def parse_args():
    parser = argparse.ArgumentParser(description="Fine-tune DistilBERT for GitHub repo classification")
    parser.add_argument("--data_path", type=str, default="data/repos.csv",
                        help="Path to CSV with columns: text_representation, label")
    parser.add_argument("--output_dir", type=str, default="./results",
                        help="Directory for Trainer checkpoints and logs")
    parser.add_argument("--model_dir", type=str, default="./model",
                        help="Directory to save the final model and tokenizer")
    parser.add_argument("--num_epochs", type=int, default=5)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument("--max_length", type=int, default=512)
    parser.add_argument("--learning_rate", type=float, default=2e-5)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--warmup_ratio", type=float, default=0.1)
    parser.add_argument("--early_stopping_patience", type=int, default=3)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()

# ---------------------------------------------------------------------------
# Data loading & splitting
# ---------------------------------------------------------------------------

def load_and_split(data_path: str, seed: int) -> tuple:
    """Load CSV and return stratified 70 / 15 / 15 splits."""
    df = pd.read_csv(data_path)

    required = {"text_representation", "label"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Dataset is missing columns: {missing}")

    df = df.dropna(subset=["text_representation", "label"]).reset_index(drop=True)
    df["text_representation"] = df["text_representation"].astype(str)

    invalid = set(df["label"].unique()) - set(LABELS)
    if invalid:
        raise ValueError(f"Unknown labels found: {invalid}. Expected: {LABELS}")

    df["label_id"] = df["label"].map(LABEL2ID)

    # 70 % train — 30 % temp
    train_df, temp_df = train_test_split(
        df, test_size=0.30, random_state=seed, stratify=df["label_id"]
    )
    # 50 % of temp → 15 % val, 15 % test
    val_df, test_df = train_test_split(
        temp_df, test_size=0.50, random_state=seed, stratify=temp_df["label_id"]
    )

    for split_name, split_df in [("Train", train_df), ("Val", val_df), ("Test", test_df)]:
        counts = split_df["label"].value_counts().to_dict()
        print(f"{split_name:5s} ({len(split_df):>5}): {counts}")

    return (
        train_df.reset_index(drop=True),
        val_df.reset_index(drop=True),
        test_df.reset_index(drop=True),
    )

# ---------------------------------------------------------------------------
# Tokenization
# ---------------------------------------------------------------------------

def build_hf_dataset(df: pd.DataFrame, tokenizer, max_length: int) -> Dataset:
    """Convert a DataFrame to a tokenized HuggingFace Dataset."""
    raw = Dataset.from_dict({
        "text": df["text_representation"].tolist(),
        "labels": df["label_id"].tolist(),
    })

    def tokenize_batch(batch):
        return tokenizer(
            batch["text"],
            truncation=True,
            padding=False,   # dynamic padding via DataCollatorWithPadding
            max_length=max_length,
        )

    tokenized = raw.map(tokenize_batch, batched=True, remove_columns=["text"])
    tokenized.set_format("torch")
    return tokenized

# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def make_compute_metrics():
    """Return a compute_metrics closure with pre-loaded evaluate objects."""
    acc_metric = evaluate.load("accuracy")
    f1_metric = evaluate.load("f1")
    prec_metric = evaluate.load("precision")
    rec_metric = evaluate.load("recall")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        return {
            "accuracy": acc_metric.compute(
                predictions=preds, references=labels)["accuracy"],
            "f1_weighted": f1_metric.compute(
                predictions=preds, references=labels, average="weighted")["f1"],
            "precision_weighted": prec_metric.compute(
                predictions=preds, references=labels,
                average="weighted", zero_division=0)["precision"],
            "recall_weighted": rec_metric.compute(
                predictions=preds, references=labels,
                average="weighted", zero_division=0)["recall"],
        }

    return compute_metrics

# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    
    # ── Fix labels if needed ──────────────────────────────────────────
    df_check = pd.read_csv(args.data_path)
    if 'weak_label' in df_check.columns and df_check['label'].isna().all():
        label_map = {
            'emerging_technology': 'emerging',
            'mature_ecosystem': 'mature',
            'declining_technology': 'declining',
            'experimental_niche': 'experimental'
        }
        df_check['label'] = df_check['weak_label'].map(label_map)
        df_check.to_csv(args.data_path, index=False)
        print("✅ Labels auto-corregidas desde weak_label")
    # ─────────────────────────────────────────────────────────────────
    
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # ── Data ──────────────────────────────────────────────────────────────
    print("Loading and splitting dataset...")
    train_df, val_df, test_df = load_and_split(args.data_path, args.seed)

    os.makedirs(args.model_dir, exist_ok=True)
    test_save_path = os.path.join(args.model_dir, "test_set.csv")
    test_df.to_csv(test_save_path, index=False)
    print(f"Test set saved → {test_save_path}")

    # ── Tokenizer ─────────────────────────────────────────────────────────
    tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)

    train_dataset = build_hf_dataset(train_df, tokenizer, args.max_length)
    val_dataset = build_hf_dataset(val_df, tokenizer, args.max_length)

    # ── Model ─────────────────────────────────────────────────────────────
    model = DistilBertForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    # ── Training arguments ─────────────────────────────────────────────────
    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.num_epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        warmup_ratio=args.warmup_ratio,
        lr_scheduler_type="cosine",
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_dir=os.path.join(args.output_dir, "logs"),
        logging_steps=50,
        load_best_model_at_end=True,
        metric_for_best_model="f1_weighted",
        greater_is_better=True,
        fp16=(device == "cuda"),
        seed=args.seed,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=make_compute_metrics(),
        callbacks=[EarlyStoppingCallback(early_stopping_patience=args.early_stopping_patience)],
    )

    # ── Train ──────────────────────────────────────────────────────────────
    print("\nStarting training...\n")
    trainer.train()

    # ── Save ───────────────────────────────────────────────────────────────
    trainer.save_model(args.model_dir)
    tokenizer.save_pretrained(args.model_dir)

    # Persist label metadata for evaluation.py
    label_meta = {"labels": LABELS, "label2id": LABEL2ID, "id2label": ID2LABEL}
    with open(os.path.join(args.model_dir, "label_meta.json"), "w") as f:
        json.dump(label_meta, f, indent=2)

    print(f"\nModel + tokenizer saved → {args.model_dir}")

    # ── Final validation metrics ────────────────────────────────────────────
    print("\n── Validation metrics (best checkpoint) ──")
    val_metrics = trainer.evaluate(val_dataset)
    for k, v in sorted(val_metrics.items()):
        print(f"  {k:<35} {v:.4f}" if isinstance(v, float) else f"  {k:<35} {v}")

    print("\nTraining complete. Run evaluation.py to evaluate on the held-out test set.")

import sys
sys.argv = [
    'train.py',
    '--data_path', 'data/labeled/labeled_repositories.csv',
    '--output_dir', 'output/',
    '--model_dir', 'models/trained_models/',
    '--num_epochs', '3'
]

if __name__ == "__main__":
    main()

import shutil
from google.colab import files
shutil.make_archive('trained_models', 'zip', 'models/trained_models/')
files.download('trained_models.zip')
